### PR TITLE
Dotty 0.21.0-RC1

### LINKED ISSUE #41: update to Dotty 0.20
```
[error] /Users/eed3si9n/work/verify/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:22:66: value symbol is not a member of RecorderMacro.this.qctx0.tasty.TypeTree
[error]   private[this] val runtimeSym = '[RecorderRuntime[_, _]].unseal.symbol match {
[error]                                                                  ^
[error] /Users/eed3si9n/work/verify/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:30:42: value underlyingArgument is not a member of RecorderMacro.this.qctx0.tasty.Term
[error]     val termArg: Term = recording.unseal.underlyingArgument
[error]                                          ^
[error] /Users/eed3si9n/work/verify/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:49:45: value underlyingArgument is not a member of RecorderMacro.this.qctx0.tasty.Term
[error]     val expectedArg: Term = expected.unseal.underlyingArgument
[error]                                             ^
[error] /Users/eed3si9n/work/verify/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:50:39: value underlyingArgument is not a member of RecorderMacro.this.qctx0.tasty.Term
[error]     val foundArg: Term = found.unseal.underlyingArgument
[error]                                       ^
[error] /Users/eed3si9n/work/verify/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:70:26: value method is not a member of Any
[error]       val m = runtimeSym.method("resetValues").head
[error]                          ^
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #41

### CODE REVIEW

**Comment by dwijnand** [comment]
`ResolveException: Error downloading ch.epfl.lamp:dotty-staging_0.19:0.21.0-RC1`

**Comment by daddykotex** [comment]
Locally, for me, resolving works, but it does not compile:

```
sbt ++0.21.0-RC1! verifyJVM/test
[info] Compiling 31 Scala sources to /Users/david/workspace/nanotest-strawman/jvm/target/scala-0.21/classes ...
[warn] Flag -sourcepath set repeatedly
[warn] Flag -sourcepath set repeatedly
[warn] bad option '-Xlint' was ignored
[warn] bad option '-Ywarn-dead-code' was ignored
[warn] bad option '-Xlog-free-terms' was ignored
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:23:65
[error] 23 |  private[this] def runtimeSym = '[RecorderRuntime[_, _]].unseal.tpe.symbol match {
[error]    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |value tpe is not a member of RecorderMacro.this.qctx0.tasty.TypeTree - did you mean TypeTree.eq?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:31:41
[error] 31 |    val termArg: Term = recording.unseal.underlyingArgument
[error]    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |value underlyingArgument is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:50:44
[error] 50 |    val expectedArg: Term = expected.unseal.underlyingArgument
[error]    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |value underlyingArgument is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:51:38
[error] 51 |    val foundArg: Term = found.unseal.underlyingArgument
[error]    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |value underlyingArgument is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:71:25
[error] 71 |      val m = runtimeSym.method("resetValues").head
[error]    |              ^^^^^^^^^^^^^^^^^
[error]    |              value method is not a member of Any
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:72:14
[error] 72 |      runtime.select(m)
[error]    |      ^^^^^^^^^^^^^^
[error]    |     value select is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:89:25
[error] 89 |      val m = runtimeSym.method("recordExpression").head
[error]    |              ^^^^^^^^^^^^^^^^^
[error]    |              value method is not a member of Any
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:90:14
[error] 90 |      runtime.select(m)
[error]    |      ^^^^^^^^^^^^^^
[error]    |     value select is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:106:40
[error] 106 |      case Select(x@This(_), y) if expr.pos.start == x.pos.start => expr
[error]     |                                   ^^^^^^^^
[error]     |value pos is not a member of RecorderMacro.this.qctx0.tasty.Term - did you mean expr.eq?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:131:25
[error] 131 |      val m = runtimeSym.method("recordValue").head
[error]     |              ^^^^^^^^^^^^^^^^^
[error]     |              value method is not a member of Any
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:132:14
[error] 132 |      runtime.select(m)
[error]     |      ^^^^^^^^^^^^^^
[error]     |   value select is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:135:10
[error] 135 |      sym.fullName match {
[error]     |      ^^^^^^^^^^^^
[error]     |value fullName is not a member of RecorderMacro.this.qctx0.tasty.Symbol
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:144:40
[error] 144 |        case IsDefDefSymbol(sym) => sym.signature.paramSigs.nonEmpty
[error]     |                                    ^^^^^^^^^^^^^
[error]     |                                value signature is not a member of Any
[error] -- [E007] Type Mismatch Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:145:46
[error] 145 |        case IsValDefSymbol(sym) => skipIdent(sym)
[error]     |                                              ^^^
[error]     |                       Found:    (sym : Any)
[error]     |                       Required: RecorderMacro.this.qctx0.tasty.Symbol
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:149:43
[error] 149 |      case Select(_, _) if skipSelect(expr.symbol) => expr
[error]     |                                      ^^^^^^^^^^^
[error]     |   value symbol is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:151:38
[error] 151 |      case Ident(_) if skipIdent(expr.symbol) => expr
[error]     |                                 ^^^^^^^^^^^
[error]     |   value symbol is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:153:36
[error] 153 |        val tapply = recordValueSel.appliedToType(expr.tpe)
[error]     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |value appliedToType is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:153:55
[error] 153 |        val tapply = recordValueSel.appliedToType(expr.tpe)
[error]     |                                                  ^^^^^^^^
[error]     |value tpe is not a member of RecorderMacro.this.qctx0.tasty.Term - did you mean expr.eq?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:165:19
[error] 165 |    val pos = expr.pos
[error]     |              ^^^^^^^^
[error]     |value pos is not a member of RecorderMacro.this.qctx0.tasty.Tree - did you mean expr.eq?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:171:29
[error] 171 |      case Apply(x, ys) if x.symbol.fullName == "verify.asserts.RecorderRuntime.recordValue" && ys.nonEmpty =>
[error]     |                           ^^^^^^^^
[error]     |   value symbol is not a member of RecorderMacro.this.qctx0.tasty.Term
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:176:13
[error] 176 |        expr.pos.startColumn + math.max(0, expr.pos.sourceCode.indexOf(y))
[error]     |        ^^^^^^^^
[error]     |value pos is not a member of RecorderMacro.this.qctx0.tasty.Term - did you mean expr.eq?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/asserts/RecorderMacro.scala:177:36
[error] 177 |      case _                => expr.pos.startColumn
[error]     |                               ^^^^^^^^
[error]     |value pos is not a member of RecorderMacro.this.qctx0.tasty.Term - did you mean expr.eq?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:82:6
[error] 82 |    s.name.trim
[error]    |    ^^^^^^
[error]    |    value name is not a member of qctx.tasty.Symbol - did you mean s.ne?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:105:28
[error] 105 |    var owner = rootContext.owner
[error]     |                ^^^^^^^^^^^^^^^^^
[error]     |value owner is not a member of qctx.tasty.Context - did you mean Context.ne?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:113:28
[error] 113 |    val owner = rootContext.owner
[error]     |                ^^^^^^^^^^^^^^^^^
[error]     |value owner is not a member of qctx.tasty.Context - did you mean Context.ne?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:120:28
[error] 120 |    val owner = rootContext.owner
[error]     |                ^^^^^^^^^^^^^^^^^
[error]     |value owner is not a member of qctx.tasty.Context - did you mean Context.ne?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:132:28
[error] 132 |    val owner = rootContext.owner
[error]     |                ^^^^^^^^^^^^^^^^^
[error]     |value owner is not a member of qctx.tasty.Context - did you mean Context.ne?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:139:34
[error] 139 |    val name = Option(rootContext.source) match {
[error]     |                      ^^^^^^^^^^^^^^^^^^
[error]     |                    value source is not a member of qctx.tasty.Context
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:140:30
[error] 140 |      case Some(file) => file.getFileName.toString
[error]     |                         ^^^^^^^^^^^^^^^^
[error]     |                         value getFileName is not a member of Nothing
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:148:34
[error] 148 |    val path = Option(rootContext.source) match {
[error]     |                      ^^^^^^^^^^^^^^^^^^
[error]     |                    value source is not a member of qctx.tasty.Context
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:157:28
[error] 157 |    val line = rootPosition.startLine + 1
[error]     |               ^^^^^^^^^^^^^^^^^^^^^^
[error]     |               value startLine is not a member of qctx.tasty.Position
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:219:50
[error] 219 |    '{ Text($v, ${Util.literal(qctx)(rootPosition.sourceCode)}) }
[error]     |                                     ^^^^^^^^^^^^^^^^^^^^^^^
[error]     |               value sourceCode is not a member of qctx.tasty.Position
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:235:30
[error] 235 |    var current = rootContext.owner
[error]     |                  ^^^^^^^^^^^^^^^^^
[error]     |value owner is not a member of qctx.tasty.Context - did you mean Context.ne?
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:243:40
[error] 243 |          case IsClassDefSymbol(x) if x.flags.is(Flags.ModuleClass) => Chunk.Obj(_)
[error]     |                                      ^^^^^^^
[error]     |                                    value flags is not a member of Any
[error] -- [E008] Member Not Found Error: /Users/david/workspace/nanotest-strawman/shared/src/main/scala-3/verify/sourcecode/Macros.scala:244:40
[error] 244 |          case IsClassDefSymbol(x) if x.flags.is(Flags.Trait) => Chunk.Trt(_)
[error]     |                                      ^^^^^^^
[error]     |                                    value flags is not a member of Any
[warn] -- Feature Warning: /Users/david/workspace/nanotest-strawman/shared/src/main/scala/verify/DiffUtil.scala:34:42
[warn] 34 |        } else if (Character.isAlphabetic(head) || Character.isDigit(head))
[warn]    |                                          ^^^^
[warn]    |Use of implicit conversion method char2int in object Char should be enabled
[warn]    |by adding the import clause 'import scala.language.implicitConversions'
[warn]    |or by setting the compiler option -language:implicitConversions.
[warn]    |See the Scala docs for value scala.language.implicitConversions for a discussion
[warn]    |why the feature should be explicitly enabled.
[warn] -- Feature Warning: /Users/david/workspace/nanotest-strawman/shared/src/main/scala/verify/DiffUtil.scala:35:47
[warn] 35 |          str.span(c => Character.isAlphabetic(c) || Character.isDigit(c) && c != ansiColorToken)
[warn]    |                                               ^
[warn]    |Use of implicit conversion method char2int in object Char should be enabled
[warn]    |by adding the import clause 'import scala.language.implicitConversions'
[warn]    |or by setting the compiler option -language:implicitConversions.
[warn]    |See the Scala docs for value scala.language.implicitConversions for a discussion
[warn]    |why the feature should be explicitly enabled.
[warn] -- Feature Warning: /Users/david/workspace/nanotest-strawman/shared/src/main/scala/verify/DiffUtil.scala:40:36
[warn] 40 |            !Character.isAlphabetic(c) && !Character.isDigit(c) &&
[warn]    |                                    ^
[warn]    |Use of implicit conversion method char2int in object Char should be enabled
[warn]    |by adding the import clause 'import scala.language.implicitConversions'
[warn]    |or by setting the compiler option -language:implicitConversions.
[warn]    |See the Scala docs for value scala.language.implicitConversions for a discussion
[warn]    |why the feature should be explicitly enabled.
[warn] 8 warnings found
[error] 35 errors found
[error] (verifyJVM / Compile / compileIncremental) Compilation failed
[error] Total time: 7 s, completed 6-Jan-2020 2:00:24 PM
```

**Comment by dwijnand** [comment]
-.-  this library should really just lose the pointless macro.

**Comment by eed3si9n** [comment]
I have no idea why it felt like everything compiled before. In any case, trying this again.
I don't think macro on its own is bad. It's just that it's annoying to track API changes by reading the Dotty code every time it changes.

**Comment by eed3si9n** [comment]
Looks like many of the failure is related to `import A._` no longer importing "given" instances. So I guess that's more of a language change.

**Pull request merged**
