### PR TITLE
use sbt logs

### LINKED ISSUE #20: Output is not printed as sbt info messages and mixed with supershell output
Please see samples of output for [this PR](https://github.com/pathikrit/dijon/pull/38):

```
[info] Compiling 1 Scala source to /home/andriy/Projects/com/github/plokhotnyuk/dijon/target/scala-2.12/test-classes ...
com.github.pathikrit.dijon.DijonSpec
- parse and serialize JSON objects
- parse and serialize JSON arrays
- handle JSON updates
- handle nulls
- handle mergesTest / executeTests 0s
- be type-safeish
- grow arrays
- not parse invalid JSON
- parse empty object
- tolerate special symbols
- do merges for non-objects
- ignore sets on primitives
- hashcode works correctly
- handle multi-line strings correct
- handle quotes in string keys
- handle numbers represented as integers
- do deep copy
[info] Passed: Total 17, Failed 0, Errors 0, Passed 17
[success] Total time: 7 s, completed Aug 13, 2019 6:20:36 AM
[info] Reapplying settings...
[info] Set current project to dijon (in build file:/home/andriy/Projects/com/github/plokhotnyuk/dijon/)
```
or
```
[info] Compiling 1 Scala source to /home/andriy/Projects/com/github/plokhotnyuk/dijon/target/scala-2.13/test-classes ...
com.github.pathikrit.dijon.DijonSpec
- parse and serialize JSON objects
- parse and serialize JSON arrays
- handle JSON updates
- handle nulls
- handle mergesTest / executeTests 0s
- be type-safeish
- grow arrays
- not parse invalid JSON
- parse empty object
- tolerate special symbols *** FAILED ***
  assertion failed
  
  assert(json.★ == 24)
         |      |
         23     false executeTests 0s
    verify.asserts.PowerAssert$AssertListener.expressionRecorded(PowerAssert.scala:38)
    verify.asserts.RecorderRuntime.recordExpression(RecorderRuntime.scala:39)
    com.github.pathikrit.dijon.DijonSpec$.$anonfun$new$108(DijonSpec.scala:336)
    verify.BasicTestSuite.$anonfun$test$1(BasicTestSuite.scala:23)
    verify.TestSpec$.$anonfun$sync$1(TestSpec.scala:48)
    verify.TestSpec.apply(TestSpec.scala:22)
    verify.Properties.$anonfun$iterator$2(Properties.scala:34)
    verify.TestSpec.apply(TestSpec.scala:22)
    verify.runner.Task.loop$1(Task.scala:52)
    verify.runner.Task.$anonfun$execute$1(Task.scala:59)
    scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
    java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
- do merges for non-objects
- ignore sets on primitives
- hashcode works correctly
- handle multi-line strings correct
- handle quotes in string keys
- handle numbers represented as integers
- do deep copy
[error] Failed: Total 17, Failed 1, Errors 0, Passed 16
[error] Failed tests:
[error]         com.github.pathikrit.dijon.DijonSpec
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed Aug 13, 2019 9:43:50 AM
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #20

### CODE REVIEW

**Comment by alexandru** [comment]
@eed3si9n @SethTisue note that the reason this setting was there and why we're using `println` is that logging output managed via SBT is printed all at once, per test suite and not line by line.

This is a problem for expensive tests.

For example in Monix we've got multi-threading tests that can timeout. And if a test times out, you won't see what test did that and you won't even see the test suite that timed out, because SBT dumps the whole output only after the test suite has finished.

Printing the output via our own `println` allows us to print that output sooner.

And it might look bad, depending on environment, but at least it allows you to get a feeling for what problematic test you have.

Printing that output via SBT's loggers, without also fixing SBT's loggers, is not going to hold for long, I can guarantee you that :)

**Comment by sjrd** [comment]
@alexandru That's why there exists
```scala
logBuffered in Test := false
```
which deactivates sbt's buffering. Best used in conjunction with
```scala
parallelExecution in Test := false
```
in order to avoid the output of several threads being interleaved. (Which is why logging is buffered by default in the first place.)

**Comment by alexandru** [comment]
Ah, I remember it not working for some reason, but I'll try it again.

Thanks.

**Comment by alexandru** [comment]
Also from what I remember, ScalaTest's behavior is by default not buffered.

Can this behavior be set by default?

**Pull request merged**
