### PR TITLE
remove unneeded environment variables

### PR DESCRIPTION
**Pull request by SethTisue**
these made sense to have the way the build used to be set up,
but not the way it's set up now; afaics it's just a vestige

### CODE REVIEW

**Comment by SethTisue** [comment]
this and #167 will conflict, but it will be easy to rebase whichever one gets merged second

**Comment by eed3si9n** [comment]
https://github.com/scala/nanotest-strawman/releases/tag/v1.0.0 was cross built against multiple JSes and multiple Natives. We could drop them probably, but might need to bump minor version to do so?

**Comment by SethTisue** [comment]
I don't think there's any need. I don't see any other repos doing that and I really doubt anyone will notice.

**Comment by eed3si9n** [comment]
I don't remember where I first saw it, but it was a mini-popular pattern in 2020 Feb when Scala.JS 1 got released and Scala.JS library authors weren't immediately sure if we should drop Scala.JS 0.6 support. See for example
- https://github.com/sjrd/scala-js-jquery/blob/master/project/build.sbt
- https://github.com/scopt/scopt/blob/develop/project/plugins.sbt

It was part of CI matrix, but got commented out because there were no Scala 3.0.0-M3 for Scala.JS 0.6 - https://github.com/scala/nanotest-strawman/commit/be13d46704b4ebccfdd3851b099d8fdf94b3f207

**Comment by SethTisue** [comment]
Ah yes, SJS 0.6. I'm confident this isn't a concern anymore, now that we're over the 1.0 hump.

**Pull request merged**
